package com.bishe.examhelper.entities;

import com.bishe.examhelper.dao.DaoSession;
import de.greenrobot.dao.DaoException;

import com.bishe.examhelper.dao.AnswerQueryDao;
import com.bishe.examhelper.dao.QuerysDao;
import com.bishe.examhelper.dao.UserDao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table ANSWER_QUERY.
 */
public class AnswerQuery implements java.io.Serializable {

    private Long id;
    private String answer_content;
    private java.util.Date answer_time;
    private long user_id;
    private long query_id;

    /** Used to resolve relations */
    private transient DaoSession daoSession;

    /** Used for active entity operations. */
    private transient AnswerQueryDao myDao;

    private User user;
    private Long user__resolvedKey;

    private Querys querys;
    private Long querys__resolvedKey;


    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public AnswerQuery() {
    }

    public AnswerQuery(Long id) {
        this.id = id;
    }

    public AnswerQuery(Long id, String answer_content, java.util.Date answer_time, long user_id, long query_id) {
        this.id = id;
        this.answer_content = answer_content;
        this.answer_time = answer_time;
        this.user_id = user_id;
        this.query_id = query_id;
    }

    /** called by internal mechanisms, do not call yourself. */
    public void __setDaoSession(DaoSession daoSession) {
        this.daoSession = daoSession;
        myDao = daoSession != null ? daoSession.getAnswerQueryDao() : null;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getAnswer_content() {
        return answer_content;
    }

    public void setAnswer_content(String answer_content) {
        this.answer_content = answer_content;
    }

    public java.util.Date getAnswer_time() {
        return answer_time;
    }

    public void setAnswer_time(java.util.Date answer_time) {
        this.answer_time = answer_time;
    }

    public long getUser_id() {
        return user_id;
    }

    public void setUser_id(long user_id) {
        this.user_id = user_id;
    }

    public long getQuery_id() {
        return query_id;
    }

    public void setQuery_id(long query_id) {
        this.query_id = query_id;
    }

    /** To-one relationship, resolved on first access. */
    public User getUser() {
        long __key = this.user_id;
        if (user__resolvedKey == null || !user__resolvedKey.equals(__key)) {
            if (daoSession == null) {
                throw new DaoException("Entity is detached from DAO context");
            }
            UserDao targetDao = daoSession.getUserDao();
            User userNew = targetDao.load(__key);
            synchronized (this) {
                user = userNew;
            	user__resolvedKey = __key;
            }
        }
        return user;
    }

    public void setUser(User user) {
        if (user == null) {
            throw new DaoException("To-one property 'user_id' has not-null constraint; cannot set to-one to null");
        }
        synchronized (this) {
            this.user = user;
            user_id = user.getId();
            user__resolvedKey = user_id;
        }
    }

    /** To-one relationship, resolved on first access. */
    public Querys getQuerys() {
        long __key = this.query_id;
        if (querys__resolvedKey == null || !querys__resolvedKey.equals(__key)) {
            if (daoSession == null) {
                throw new DaoException("Entity is detached from DAO context");
            }
            QuerysDao targetDao = daoSession.getQuerysDao();
            Querys querysNew = targetDao.load(__key);
            synchronized (this) {
                querys = querysNew;
            	querys__resolvedKey = __key;
            }
        }
        return querys;
    }

    public void setQuerys(Querys querys) {
        if (querys == null) {
            throw new DaoException("To-one property 'query_id' has not-null constraint; cannot set to-one to null");
        }
        synchronized (this) {
            this.querys = querys;
            query_id = querys.getId();
            querys__resolvedKey = query_id;
        }
    }

    /** Convenient call for {@link AbstractDao#delete(Object)}. Entity must attached to an entity context. */
    public void delete() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.delete(this);
    }

    /** Convenient call for {@link AbstractDao#update(Object)}. Entity must attached to an entity context. */
    public void update() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.update(this);
    }

    /** Convenient call for {@link AbstractDao#refresh(Object)}. Entity must attached to an entity context. */
    public void refresh() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.refresh(this);
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
