package com.bishe.examhelper.dao;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.SqlUtils;
import de.greenrobot.dao.internal.DaoConfig;
import de.greenrobot.dao.query.Query;
import de.greenrobot.dao.query.QueryBuilder;

import com.bishe.examhelper.entities.Querys;
import com.bishe.examhelper.entities.User;

import com.bishe.examhelper.entities.AnswerQuery;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table ANSWER_QUERY.
*/
public class AnswerQueryDao extends AbstractDao<AnswerQuery, Long> {

    public static final String TABLENAME = "ANSWER_QUERY";

    /**
     * Properties of entity AnswerQuery.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Answer_content = new Property(1, String.class, "answer_content", false, "ANSWER_CONTENT");
        public final static Property Answer_time = new Property(2, java.util.Date.class, "answer_time", false, "ANSWER_TIME");
        public final static Property User_id = new Property(3, long.class, "user_id", false, "USER_ID");
        public final static Property Query_id = new Property(4, long.class, "query_id", false, "QUERY_ID");
    };

    private DaoSession daoSession;

    private Query<AnswerQuery> user_AnswerQueryListQuery;
    private Query<AnswerQuery> querys_AnswerQueryListQuery;

    public AnswerQueryDao(DaoConfig config) {
        super(config);
    }
    
    public AnswerQueryDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'ANSWER_QUERY' (" + //
                "'_id' INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "'ANSWER_CONTENT' TEXT," + // 1: answer_content
                "'ANSWER_TIME' INTEGER," + // 2: answer_time
                "'USER_ID' INTEGER NOT NULL ," + // 3: user_id
                "'QUERY_ID' INTEGER NOT NULL );"); // 4: query_id
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'ANSWER_QUERY'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, AnswerQuery entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String answer_content = entity.getAnswer_content();
        if (answer_content != null) {
            stmt.bindString(2, answer_content);
        }
 
        java.util.Date answer_time = entity.getAnswer_time();
        if (answer_time != null) {
            stmt.bindLong(3, answer_time.getTime());
        }
        stmt.bindLong(4, entity.getUser_id());
        stmt.bindLong(5, entity.getQuery_id());
    }

    @Override
    protected void attachEntity(AnswerQuery entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public AnswerQuery readEntity(Cursor cursor, int offset) {
        AnswerQuery entity = new AnswerQuery( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // answer_content
            cursor.isNull(offset + 2) ? null : new java.util.Date(cursor.getLong(offset + 2)), // answer_time
            cursor.getLong(offset + 3), // user_id
            cursor.getLong(offset + 4) // query_id
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, AnswerQuery entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setAnswer_content(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setAnswer_time(cursor.isNull(offset + 2) ? null : new java.util.Date(cursor.getLong(offset + 2)));
        entity.setUser_id(cursor.getLong(offset + 3));
        entity.setQuery_id(cursor.getLong(offset + 4));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(AnswerQuery entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(AnswerQuery entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "answerQueryList" to-many relationship of User. */
    public List<AnswerQuery> _queryUser_AnswerQueryList(long user_id) {
        synchronized (this) {
            if (user_AnswerQueryListQuery == null) {
                QueryBuilder<AnswerQuery> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.User_id.eq(null));
                user_AnswerQueryListQuery = queryBuilder.build();
            }
        }
        Query<AnswerQuery> query = user_AnswerQueryListQuery.forCurrentThread();
        query.setParameter(0, user_id);
        return query.list();
    }

    /** Internal query to resolve the "answerQueryList" to-many relationship of Querys. */
    public List<AnswerQuery> _queryQuerys_AnswerQueryList(long query_id) {
        synchronized (this) {
            if (querys_AnswerQueryListQuery == null) {
                QueryBuilder<AnswerQuery> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.Query_id.eq(null));
                querys_AnswerQueryListQuery = queryBuilder.build();
            }
        }
        Query<AnswerQuery> query = querys_AnswerQueryListQuery.forCurrentThread();
        query.setParameter(0, query_id);
        return query.list();
    }

    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getUserDao().getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T1", daoSession.getQuerysDao().getAllColumns());
            builder.append(" FROM ANSWER_QUERY T");
            builder.append(" LEFT JOIN USER T0 ON T.'USER_ID'=T0.'_id'");
            builder.append(" LEFT JOIN QUERYS T1 ON T.'QUERY_ID'=T1.'_id'");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected AnswerQuery loadCurrentDeep(Cursor cursor, boolean lock) {
        AnswerQuery entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        User user = loadCurrentOther(daoSession.getUserDao(), cursor, offset);
         if(user != null) {
            entity.setUser(user);
        }
        offset += daoSession.getUserDao().getAllColumns().length;

        Querys querys = loadCurrentOther(daoSession.getQuerysDao(), cursor, offset);
         if(querys != null) {
            entity.setQuerys(querys);
        }

        return entity;    
    }

    public AnswerQuery loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<AnswerQuery> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<AnswerQuery> list = new ArrayList<AnswerQuery>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<AnswerQuery> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<AnswerQuery> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
