package com.bishe.examhelper.dao;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.SqlUtils;
import de.greenrobot.dao.internal.DaoConfig;
import de.greenrobot.dao.query.Query;
import de.greenrobot.dao.query.QueryBuilder;

import com.bishe.examhelper.entities.QuestionType;
import com.bishe.examhelper.entities.Section;
import com.bishe.examhelper.entities.User;

import com.bishe.examhelper.entities.ErrorQuestions;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table ERROR_QUESTIONS.
*/
public class ErrorQuestionsDao extends AbstractDao<ErrorQuestions, Long> {

    public static final String TABLENAME = "ERROR_QUESTIONS";

    /**
     * Properties of entity ErrorQuestions.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Question_id = new Property(1, long.class, "question_id", false, "QUESTION_ID");
        public final static Property Error_time = new Property(2, java.util.Date.class, "error_time", false, "ERROR_TIME");
        public final static Property Error_num = new Property(3, Integer.class, "error_num", false, "ERROR_NUM");
        public final static Property User_id = new Property(4, long.class, "user_id", false, "USER_ID");
        public final static Property QuestionType_id = new Property(5, long.class, "questionType_id", false, "QUESTION_TYPE_ID");
        public final static Property Section_id = new Property(6, long.class, "section_id", false, "SECTION_ID");
    };

    private DaoSession daoSession;

    private Query<ErrorQuestions> user_ErrorQuestionsListQuery;
    private Query<ErrorQuestions> questionType_ErrorQuestionsListQuery;
    private Query<ErrorQuestions> section_ErrorQuestionsListQuery;

    public ErrorQuestionsDao(DaoConfig config) {
        super(config);
    }
    
    public ErrorQuestionsDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'ERROR_QUESTIONS' (" + //
                "'_id' INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "'QUESTION_ID' INTEGER NOT NULL ," + // 1: question_id
                "'ERROR_TIME' INTEGER," + // 2: error_time
                "'ERROR_NUM' INTEGER," + // 3: error_num
                "'USER_ID' INTEGER NOT NULL ," + // 4: user_id
                "'QUESTION_TYPE_ID' INTEGER NOT NULL ," + // 5: questionType_id
                "'SECTION_ID' INTEGER NOT NULL );"); // 6: section_id
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'ERROR_QUESTIONS'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, ErrorQuestions entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getQuestion_id());
 
        java.util.Date error_time = entity.getError_time();
        if (error_time != null) {
            stmt.bindLong(3, error_time.getTime());
        }
 
        Integer error_num = entity.getError_num();
        if (error_num != null) {
            stmt.bindLong(4, error_num);
        }
        stmt.bindLong(5, entity.getUser_id());
        stmt.bindLong(6, entity.getQuestionType_id());
        stmt.bindLong(7, entity.getSection_id());
    }

    @Override
    protected void attachEntity(ErrorQuestions entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public ErrorQuestions readEntity(Cursor cursor, int offset) {
        ErrorQuestions entity = new ErrorQuestions( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getLong(offset + 1), // question_id
            cursor.isNull(offset + 2) ? null : new java.util.Date(cursor.getLong(offset + 2)), // error_time
            cursor.isNull(offset + 3) ? null : cursor.getInt(offset + 3), // error_num
            cursor.getLong(offset + 4), // user_id
            cursor.getLong(offset + 5), // questionType_id
            cursor.getLong(offset + 6) // section_id
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, ErrorQuestions entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setQuestion_id(cursor.getLong(offset + 1));
        entity.setError_time(cursor.isNull(offset + 2) ? null : new java.util.Date(cursor.getLong(offset + 2)));
        entity.setError_num(cursor.isNull(offset + 3) ? null : cursor.getInt(offset + 3));
        entity.setUser_id(cursor.getLong(offset + 4));
        entity.setQuestionType_id(cursor.getLong(offset + 5));
        entity.setSection_id(cursor.getLong(offset + 6));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(ErrorQuestions entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(ErrorQuestions entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "errorQuestionsList" to-many relationship of User. */
    public List<ErrorQuestions> _queryUser_ErrorQuestionsList(long user_id) {
        synchronized (this) {
            if (user_ErrorQuestionsListQuery == null) {
                QueryBuilder<ErrorQuestions> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.User_id.eq(null));
                user_ErrorQuestionsListQuery = queryBuilder.build();
            }
        }
        Query<ErrorQuestions> query = user_ErrorQuestionsListQuery.forCurrentThread();
        query.setParameter(0, user_id);
        return query.list();
    }

    /** Internal query to resolve the "errorQuestionsList" to-many relationship of QuestionType. */
    public List<ErrorQuestions> _queryQuestionType_ErrorQuestionsList(long questionType_id) {
        synchronized (this) {
            if (questionType_ErrorQuestionsListQuery == null) {
                QueryBuilder<ErrorQuestions> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.QuestionType_id.eq(null));
                questionType_ErrorQuestionsListQuery = queryBuilder.build();
            }
        }
        Query<ErrorQuestions> query = questionType_ErrorQuestionsListQuery.forCurrentThread();
        query.setParameter(0, questionType_id);
        return query.list();
    }

    /** Internal query to resolve the "errorQuestionsList" to-many relationship of Section. */
    public List<ErrorQuestions> _querySection_ErrorQuestionsList(long section_id) {
        synchronized (this) {
            if (section_ErrorQuestionsListQuery == null) {
                QueryBuilder<ErrorQuestions> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.Section_id.eq(null));
                section_ErrorQuestionsListQuery = queryBuilder.build();
            }
        }
        Query<ErrorQuestions> query = section_ErrorQuestionsListQuery.forCurrentThread();
        query.setParameter(0, section_id);
        return query.list();
    }

    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getUserDao().getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T1", daoSession.getQuestionTypeDao().getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T2", daoSession.getSectionDao().getAllColumns());
            builder.append(" FROM ERROR_QUESTIONS T");
            builder.append(" LEFT JOIN USER T0 ON T.'USER_ID'=T0.'_id'");
            builder.append(" LEFT JOIN QUESTION_TYPE T1 ON T.'QUESTION_TYPE_ID'=T1.'_id'");
            builder.append(" LEFT JOIN SECTION T2 ON T.'SECTION_ID'=T2.'_id'");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected ErrorQuestions loadCurrentDeep(Cursor cursor, boolean lock) {
        ErrorQuestions entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        User user = loadCurrentOther(daoSession.getUserDao(), cursor, offset);
         if(user != null) {
            entity.setUser(user);
        }
        offset += daoSession.getUserDao().getAllColumns().length;

        QuestionType questionType = loadCurrentOther(daoSession.getQuestionTypeDao(), cursor, offset);
         if(questionType != null) {
            entity.setQuestionType(questionType);
        }
        offset += daoSession.getQuestionTypeDao().getAllColumns().length;

        Section section = loadCurrentOther(daoSession.getSectionDao(), cursor, offset);
         if(section != null) {
            entity.setSection(section);
        }

        return entity;    
    }

    public ErrorQuestions loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<ErrorQuestions> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<ErrorQuestions> list = new ArrayList<ErrorQuestions>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<ErrorQuestions> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<ErrorQuestions> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
