package com.bishe.examhelper.dao;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.SqlUtils;
import de.greenrobot.dao.internal.DaoConfig;
import de.greenrobot.dao.query.Query;
import de.greenrobot.dao.query.QueryBuilder;

import com.bishe.examhelper.entities.Section;

import com.bishe.examhelper.entities.MaterialAnalysis;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table MATERIAL_ANALYSIS.
*/
public class MaterialAnalysisDao extends AbstractDao<MaterialAnalysis, Long> {

    public static final String TABLENAME = "MATERIAL_ANALYSIS";

    /**
     * Properties of entity MaterialAnalysis.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Material = new Property(1, String.class, "material", false, "MATERIAL");
        public final static Property Material_image = new Property(2, String.class, "material_image", false, "MATERIAL_IMAGE");
        public final static Property Remark = new Property(3, String.class, "remark", false, "REMARK");
        public final static Property Flag = new Property(4, Boolean.class, "flag", false, "FLAG");
        public final static Property Section_id = new Property(5, long.class, "section_id", false, "SECTION_ID");
    };

    private DaoSession daoSession;

    private Query<MaterialAnalysis> section_MaterialAnalysisListQuery;

    public MaterialAnalysisDao(DaoConfig config) {
        super(config);
    }
    
    public MaterialAnalysisDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'MATERIAL_ANALYSIS' (" + //
                "'_id' INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "'MATERIAL' TEXT NOT NULL ," + // 1: material
                "'MATERIAL_IMAGE' TEXT," + // 2: material_image
                "'REMARK' TEXT," + // 3: remark
                "'FLAG' INTEGER," + // 4: flag
                "'SECTION_ID' INTEGER NOT NULL );"); // 5: section_id
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'MATERIAL_ANALYSIS'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, MaterialAnalysis entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindString(2, entity.getMaterial());
 
        String material_image = entity.getMaterial_image();
        if (material_image != null) {
            stmt.bindString(3, material_image);
        }
 
        String remark = entity.getRemark();
        if (remark != null) {
            stmt.bindString(4, remark);
        }
 
        Boolean flag = entity.getFlag();
        if (flag != null) {
            stmt.bindLong(5, flag ? 1l: 0l);
        }
        stmt.bindLong(6, entity.getSection_id());
    }

    @Override
    protected void attachEntity(MaterialAnalysis entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public MaterialAnalysis readEntity(Cursor cursor, int offset) {
        MaterialAnalysis entity = new MaterialAnalysis( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getString(offset + 1), // material
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // material_image
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // remark
            cursor.isNull(offset + 4) ? null : cursor.getShort(offset + 4) != 0, // flag
            cursor.getLong(offset + 5) // section_id
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, MaterialAnalysis entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setMaterial(cursor.getString(offset + 1));
        entity.setMaterial_image(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setRemark(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setFlag(cursor.isNull(offset + 4) ? null : cursor.getShort(offset + 4) != 0);
        entity.setSection_id(cursor.getLong(offset + 5));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(MaterialAnalysis entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(MaterialAnalysis entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "MaterialAnalysisList" to-many relationship of Section. */
    public List<MaterialAnalysis> _querySection_MaterialAnalysisList(long section_id) {
        synchronized (this) {
            if (section_MaterialAnalysisListQuery == null) {
                QueryBuilder<MaterialAnalysis> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.Section_id.eq(null));
                section_MaterialAnalysisListQuery = queryBuilder.build();
            }
        }
        Query<MaterialAnalysis> query = section_MaterialAnalysisListQuery.forCurrentThread();
        query.setParameter(0, section_id);
        return query.list();
    }

    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getSectionDao().getAllColumns());
            builder.append(" FROM MATERIAL_ANALYSIS T");
            builder.append(" LEFT JOIN SECTION T0 ON T.'SECTION_ID'=T0.'_id'");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected MaterialAnalysis loadCurrentDeep(Cursor cursor, boolean lock) {
        MaterialAnalysis entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        Section section = loadCurrentOther(daoSession.getSectionDao(), cursor, offset);
         if(section != null) {
            entity.setSection(section);
        }

        return entity;    
    }

    public MaterialAnalysis loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<MaterialAnalysis> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<MaterialAnalysis> list = new ArrayList<MaterialAnalysis>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<MaterialAnalysis> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<MaterialAnalysis> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
