package com.bishe.examhelper.dao;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.SqlUtils;
import de.greenrobot.dao.internal.DaoConfig;
import de.greenrobot.dao.query.Query;
import de.greenrobot.dao.query.QueryBuilder;

import com.bishe.examhelper.entities.QuestionType;
import com.bishe.examhelper.entities.User;

import com.bishe.examhelper.entities.Querys;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table QUERYS.
*/
public class QuerysDao extends AbstractDao<Querys, Long> {

    public static final String TABLENAME = "QUERYS";

    /**
     * Properties of entity Querys.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Question_id = new Property(1, long.class, "question_id", false, "QUESTION_ID");
        public final static Property Query_time = new Property(2, java.util.Date.class, "query_time", false, "QUERY_TIME");
        public final static Property Query_stem = new Property(3, String.class, "query_stem", false, "QUERY_STEM");
        public final static Property Integral = new Property(4, Integer.class, "integral", false, "INTEGRAL");
        public final static Property Adopt_user_id = new Property(5, Long.class, "adopt_user_id", false, "ADOPT_USER_ID");
        public final static Property User_id = new Property(6, long.class, "user_id", false, "USER_ID");
        public final static Property QuestionType_id = new Property(7, long.class, "questionType_id", false, "QUESTION_TYPE_ID");
    };

    private DaoSession daoSession;

    private Query<Querys> user_QueryListQuery;
    private Query<Querys> questionType_QueryListQuery;

    public QuerysDao(DaoConfig config) {
        super(config);
    }
    
    public QuerysDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'QUERYS' (" + //
                "'_id' INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "'QUESTION_ID' INTEGER NOT NULL ," + // 1: question_id
                "'QUERY_TIME' INTEGER," + // 2: query_time
                "'QUERY_STEM' TEXT," + // 3: query_stem
                "'INTEGRAL' INTEGER," + // 4: integral
                "'ADOPT_USER_ID' INTEGER," + // 5: adopt_user_id
                "'USER_ID' INTEGER NOT NULL ," + // 6: user_id
                "'QUESTION_TYPE_ID' INTEGER NOT NULL );"); // 7: questionType_id
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'QUERYS'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, Querys entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getQuestion_id());
 
        java.util.Date query_time = entity.getQuery_time();
        if (query_time != null) {
            stmt.bindLong(3, query_time.getTime());
        }
 
        String query_stem = entity.getQuery_stem();
        if (query_stem != null) {
            stmt.bindString(4, query_stem);
        }
 
        Integer integral = entity.getIntegral();
        if (integral != null) {
            stmt.bindLong(5, integral);
        }
 
        Long adopt_user_id = entity.getAdopt_user_id();
        if (adopt_user_id != null) {
            stmt.bindLong(6, adopt_user_id);
        }
        stmt.bindLong(7, entity.getUser_id());
        stmt.bindLong(8, entity.getQuestionType_id());
    }

    @Override
    protected void attachEntity(Querys entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public Querys readEntity(Cursor cursor, int offset) {
        Querys entity = new Querys( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getLong(offset + 1), // question_id
            cursor.isNull(offset + 2) ? null : new java.util.Date(cursor.getLong(offset + 2)), // query_time
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // query_stem
            cursor.isNull(offset + 4) ? null : cursor.getInt(offset + 4), // integral
            cursor.isNull(offset + 5) ? null : cursor.getLong(offset + 5), // adopt_user_id
            cursor.getLong(offset + 6), // user_id
            cursor.getLong(offset + 7) // questionType_id
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, Querys entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setQuestion_id(cursor.getLong(offset + 1));
        entity.setQuery_time(cursor.isNull(offset + 2) ? null : new java.util.Date(cursor.getLong(offset + 2)));
        entity.setQuery_stem(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setIntegral(cursor.isNull(offset + 4) ? null : cursor.getInt(offset + 4));
        entity.setAdopt_user_id(cursor.isNull(offset + 5) ? null : cursor.getLong(offset + 5));
        entity.setUser_id(cursor.getLong(offset + 6));
        entity.setQuestionType_id(cursor.getLong(offset + 7));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(Querys entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(Querys entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "queryList" to-many relationship of User. */
    public List<Querys> _queryUser_QueryList(long user_id) {
        synchronized (this) {
            if (user_QueryListQuery == null) {
                QueryBuilder<Querys> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.User_id.eq(null));
                user_QueryListQuery = queryBuilder.build();
            }
        }
        Query<Querys> query = user_QueryListQuery.forCurrentThread();
        query.setParameter(0, user_id);
        return query.list();
    }

    /** Internal query to resolve the "queryList" to-many relationship of QuestionType. */
    public List<Querys> _queryQuestionType_QueryList(long questionType_id) {
        synchronized (this) {
            if (questionType_QueryListQuery == null) {
                QueryBuilder<Querys> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.QuestionType_id.eq(null));
                questionType_QueryListQuery = queryBuilder.build();
            }
        }
        Query<Querys> query = questionType_QueryListQuery.forCurrentThread();
        query.setParameter(0, questionType_id);
        return query.list();
    }

    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getUserDao().getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T1", daoSession.getQuestionTypeDao().getAllColumns());
            builder.append(" FROM QUERYS T");
            builder.append(" LEFT JOIN USER T0 ON T.'USER_ID'=T0.'_id'");
            builder.append(" LEFT JOIN QUESTION_TYPE T1 ON T.'QUESTION_TYPE_ID'=T1.'_id'");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected Querys loadCurrentDeep(Cursor cursor, boolean lock) {
        Querys entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        User user = loadCurrentOther(daoSession.getUserDao(), cursor, offset);
         if(user != null) {
            entity.setUser(user);
        }
        offset += daoSession.getUserDao().getAllColumns().length;

        QuestionType questionType = loadCurrentOther(daoSession.getQuestionTypeDao(), cursor, offset);
         if(questionType != null) {
            entity.setQuestionType(questionType);
        }

        return entity;    
    }

    public Querys loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<Querys> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<Querys> list = new ArrayList<Querys>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<Querys> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<Querys> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
