package com.bishe.examhelper.dao;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.SqlUtils;
import de.greenrobot.dao.internal.DaoConfig;
import de.greenrobot.dao.query.Query;
import de.greenrobot.dao.query.QueryBuilder;

import com.bishe.examhelper.entities.Section;

import com.bishe.examhelper.entities.SingleChoice;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table SINGLE_CHOICE.
*/
public class SingleChoiceDao extends AbstractDao<SingleChoice, Long> {

    public static final String TABLENAME = "SINGLE_CHOICE";

    /**
     * Properties of entity SingleChoice.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Question_stem = new Property(1, String.class, "question_stem", false, "QUESTION_STEM");
        public final static Property OptionA = new Property(2, String.class, "optionA", false, "OPTION_A");
        public final static Property OptionB = new Property(3, String.class, "optionB", false, "OPTION_B");
        public final static Property OptionC = new Property(4, String.class, "optionC", false, "OPTION_C");
        public final static Property OptionD = new Property(5, String.class, "optionD", false, "OPTION_D");
        public final static Property OptionE = new Property(6, String.class, "optionE", false, "OPTION_E");
        public final static Property Answer = new Property(7, String.class, "answer", false, "ANSWER");
        public final static Property Analysis = new Property(8, String.class, "analysis", false, "ANALYSIS");
        public final static Property Remark = new Property(9, String.class, "remark", false, "REMARK");
        public final static Property Flag = new Property(10, Boolean.class, "flag", false, "FLAG");
        public final static Property Section_id = new Property(11, long.class, "section_id", false, "SECTION_ID");
    };

    private DaoSession daoSession;

    private Query<SingleChoice> section_SingleChoiceListQuery;

    public SingleChoiceDao(DaoConfig config) {
        super(config);
    }
    
    public SingleChoiceDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'SINGLE_CHOICE' (" + //
                "'_id' INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "'QUESTION_STEM' TEXT NOT NULL ," + // 1: question_stem
                "'OPTION_A' TEXT," + // 2: optionA
                "'OPTION_B' TEXT," + // 3: optionB
                "'OPTION_C' TEXT," + // 4: optionC
                "'OPTION_D' TEXT," + // 5: optionD
                "'OPTION_E' TEXT," + // 6: optionE
                "'ANSWER' TEXT," + // 7: answer
                "'ANALYSIS' TEXT," + // 8: analysis
                "'REMARK' TEXT," + // 9: remark
                "'FLAG' INTEGER," + // 10: flag
                "'SECTION_ID' INTEGER NOT NULL );"); // 11: section_id
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'SINGLE_CHOICE'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, SingleChoice entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindString(2, entity.getQuestion_stem());
 
        String optionA = entity.getOptionA();
        if (optionA != null) {
            stmt.bindString(3, optionA);
        }
 
        String optionB = entity.getOptionB();
        if (optionB != null) {
            stmt.bindString(4, optionB);
        }
 
        String optionC = entity.getOptionC();
        if (optionC != null) {
            stmt.bindString(5, optionC);
        }
 
        String optionD = entity.getOptionD();
        if (optionD != null) {
            stmt.bindString(6, optionD);
        }
 
        String optionE = entity.getOptionE();
        if (optionE != null) {
            stmt.bindString(7, optionE);
        }
 
        String answer = entity.getAnswer();
        if (answer != null) {
            stmt.bindString(8, answer);
        }
 
        String analysis = entity.getAnalysis();
        if (analysis != null) {
            stmt.bindString(9, analysis);
        }
 
        String remark = entity.getRemark();
        if (remark != null) {
            stmt.bindString(10, remark);
        }
 
        Boolean flag = entity.getFlag();
        if (flag != null) {
            stmt.bindLong(11, flag ? 1l: 0l);
        }
        stmt.bindLong(12, entity.getSection_id());
    }

    @Override
    protected void attachEntity(SingleChoice entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public SingleChoice readEntity(Cursor cursor, int offset) {
        SingleChoice entity = new SingleChoice( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getString(offset + 1), // question_stem
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // optionA
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // optionB
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // optionC
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // optionD
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // optionE
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // answer
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8), // analysis
            cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9), // remark
            cursor.isNull(offset + 10) ? null : cursor.getShort(offset + 10) != 0, // flag
            cursor.getLong(offset + 11) // section_id
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, SingleChoice entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setQuestion_stem(cursor.getString(offset + 1));
        entity.setOptionA(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setOptionB(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setOptionC(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setOptionD(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setOptionE(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setAnswer(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setAnalysis(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
        entity.setRemark(cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9));
        entity.setFlag(cursor.isNull(offset + 10) ? null : cursor.getShort(offset + 10) != 0);
        entity.setSection_id(cursor.getLong(offset + 11));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(SingleChoice entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(SingleChoice entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "singleChoiceList" to-many relationship of Section. */
    public List<SingleChoice> _querySection_SingleChoiceList(long section_id) {
        synchronized (this) {
            if (section_SingleChoiceListQuery == null) {
                QueryBuilder<SingleChoice> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.Section_id.eq(null));
                section_SingleChoiceListQuery = queryBuilder.build();
            }
        }
        Query<SingleChoice> query = section_SingleChoiceListQuery.forCurrentThread();
        query.setParameter(0, section_id);
        return query.list();
    }

    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getSectionDao().getAllColumns());
            builder.append(" FROM SINGLE_CHOICE T");
            builder.append(" LEFT JOIN SECTION T0 ON T.'SECTION_ID'=T0.'_id'");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected SingleChoice loadCurrentDeep(Cursor cursor, boolean lock) {
        SingleChoice entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        Section section = loadCurrentOther(daoSession.getSectionDao(), cursor, offset);
         if(section != null) {
            entity.setSection(section);
        }

        return entity;    
    }

    public SingleChoice loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<SingleChoice> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<SingleChoice> list = new ArrayList<SingleChoice>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<SingleChoice> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<SingleChoice> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
