package com.bishe.examhelper.dao;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.SqlUtils;
import de.greenrobot.dao.internal.DaoConfig;
import de.greenrobot.dao.query.Query;
import de.greenrobot.dao.query.QueryBuilder;

import com.bishe.examhelper.entities.Section;

import com.bishe.examhelper.entities.TrueOrFalse;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table TRUE_OR_FALSE.
*/
public class TrueOrFalseDao extends AbstractDao<TrueOrFalse, Long> {

    public static final String TABLENAME = "TRUE_OR_FALSE";

    /**
     * Properties of entity TrueOrFalse.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Question_stem = new Property(1, String.class, "question_stem", false, "QUESTION_STEM");
        public final static Property Answer = new Property(2, Boolean.class, "answer", false, "ANSWER");
        public final static Property Analysis = new Property(3, String.class, "analysis", false, "ANALYSIS");
        public final static Property Remark = new Property(4, String.class, "remark", false, "REMARK");
        public final static Property Flag = new Property(5, Boolean.class, "flag", false, "FLAG");
        public final static Property Section_id = new Property(6, long.class, "section_id", false, "SECTION_ID");
    };

    private DaoSession daoSession;

    private Query<TrueOrFalse> section_TrueOrFalseListQuery;

    public TrueOrFalseDao(DaoConfig config) {
        super(config);
    }
    
    public TrueOrFalseDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'TRUE_OR_FALSE' (" + //
                "'_id' INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "'QUESTION_STEM' TEXT NOT NULL ," + // 1: question_stem
                "'ANSWER' INTEGER," + // 2: answer
                "'ANALYSIS' TEXT," + // 3: analysis
                "'REMARK' TEXT," + // 4: remark
                "'FLAG' INTEGER," + // 5: flag
                "'SECTION_ID' INTEGER NOT NULL );"); // 6: section_id
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'TRUE_OR_FALSE'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, TrueOrFalse entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindString(2, entity.getQuestion_stem());
 
        Boolean answer = entity.getAnswer();
        if (answer != null) {
            stmt.bindLong(3, answer ? 1l: 0l);
        }
 
        String analysis = entity.getAnalysis();
        if (analysis != null) {
            stmt.bindString(4, analysis);
        }
 
        String remark = entity.getRemark();
        if (remark != null) {
            stmt.bindString(5, remark);
        }
 
        Boolean flag = entity.getFlag();
        if (flag != null) {
            stmt.bindLong(6, flag ? 1l: 0l);
        }
        stmt.bindLong(7, entity.getSection_id());
    }

    @Override
    protected void attachEntity(TrueOrFalse entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public TrueOrFalse readEntity(Cursor cursor, int offset) {
        TrueOrFalse entity = new TrueOrFalse( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getString(offset + 1), // question_stem
            cursor.isNull(offset + 2) ? null : cursor.getShort(offset + 2) != 0, // answer
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // analysis
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // remark
            cursor.isNull(offset + 5) ? null : cursor.getShort(offset + 5) != 0, // flag
            cursor.getLong(offset + 6) // section_id
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, TrueOrFalse entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setQuestion_stem(cursor.getString(offset + 1));
        entity.setAnswer(cursor.isNull(offset + 2) ? null : cursor.getShort(offset + 2) != 0);
        entity.setAnalysis(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setRemark(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setFlag(cursor.isNull(offset + 5) ? null : cursor.getShort(offset + 5) != 0);
        entity.setSection_id(cursor.getLong(offset + 6));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(TrueOrFalse entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(TrueOrFalse entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "trueOrFalseList" to-many relationship of Section. */
    public List<TrueOrFalse> _querySection_TrueOrFalseList(long section_id) {
        synchronized (this) {
            if (section_TrueOrFalseListQuery == null) {
                QueryBuilder<TrueOrFalse> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.Section_id.eq(null));
                section_TrueOrFalseListQuery = queryBuilder.build();
            }
        }
        Query<TrueOrFalse> query = section_TrueOrFalseListQuery.forCurrentThread();
        query.setParameter(0, section_id);
        return query.list();
    }

    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getSectionDao().getAllColumns());
            builder.append(" FROM TRUE_OR_FALSE T");
            builder.append(" LEFT JOIN SECTION T0 ON T.'SECTION_ID'=T0.'_id'");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected TrueOrFalse loadCurrentDeep(Cursor cursor, boolean lock) {
        TrueOrFalse entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        Section section = loadCurrentOther(daoSession.getSectionDao(), cursor, offset);
         if(section != null) {
            entity.setSection(section);
        }

        return entity;    
    }

    public TrueOrFalse loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<TrueOrFalse> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<TrueOrFalse> list = new ArrayList<TrueOrFalse>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<TrueOrFalse> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<TrueOrFalse> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
